version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: radthal-node_web_1
      APP_PORT: 3777

  web:
    image: python:3.12-alpine
    restart: on-failure
    stop_grace_period: 5s
    extra_hosts:
      - "radthal-host:host-gateway"
    command: ["python", "/app/radthal_ui.py"]
    volumes:
      - ${APP_DATA_DIR}/radthal_ui.py:/app/radthal_ui.py:ro
      - /home/umbrel/radthal/rpcpass.txt:/run/secrets/radthal_rpc_password:ro

    environment:
      VIEW: node
      PORT: "3777"
      RPC: "http://radthal-host:9332"
      PASSFILE: /run/secrets/radthal_rpc_password
      LOGS: /ckpool/logs
      WALLET: minage
      STRATUM_PORT: "3333"
